version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namngam-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Use the internal service name 'db' instead of IP address
      - DATABASE_URL=postgresql://${POSTGRES_USER:-namngam_user}:${POSTGRES_PASSWORD:-Te1862005}@db:5432/${POSTGRES_DB:-namngam}?schema=public
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    networks:
      - namngarm-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: namngam-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-namngam_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Te1862005}
      - POSTGRES_DB=${POSTGRES_DB:-namngam}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - namngarm-network

networks:
  namngarm-network:
    driver: bridge

volumes:
  postgres_data:
