version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namngarm-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      # Add other environment variables here
    networks:
      - namngarm-network

networks:
  namngarm-network:
    driver: bridge
